[package]
name = "mc-map-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mc-map-reader-lib = { path="../mc-map-reader-lib" }
clap = { version = "4.1.6", features = ["derive"] }
futures = "0.3.26"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
thiserror = "1.0.38"
wildmatch = "2.1.1"
rayon = "1.7.0"
